services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: buscaimoveis
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
